name: CI

on: ['push', 'pull_request']

jobs:
  build-and-test:
    name: Gradle ${{ matrix.gradle }} on Java ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11]
        gradle: ['6.9.2']
        include:
          - java: 15
            gradle: '7.3.3'
            properties: '-Pspock_version=2.0-groovy-3.0 -PgebVersion=5.0'

    env:
      TEST_ALL_CONTAINERS: "['jetty9.3','jetty9.4','tomcat85','tomcat9']"
      GRADLE_VERSION: ${{ matrix.gradle }}
      BINTRAY_REPO: maven
      BINTRAY_PACKAGE: org.gretty
      EXTRA_PROPERTIES: ${{ matrix.properties }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Cache Gradle stuff
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches/modules-2
          key: ${{ runner.os }}-build-${{ env.GRADLE_VERSION }}-${{ hashFiles('**/*.gradle', 'gradle.properties') }}

      - name: Build and Test
        run: |
          set -e
          ./gradlew --no-daemon wrapper --gradle-version $GRADLE_VERSION --distribution-type all
          ./gradlew --no-daemon --warning-mode all $EXTRA_PROPERTIES build
          cd integrationTests
          ../gradlew --no-daemon --warning-mode all $EXTRA_PROPERTIES -PgeckoDriverPlatform=linux64 -PtestAllContainers=$TEST_ALL_CONTAINERS testAll
          cd ..
          set +e
